version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sql_server
    environment:
      SA_PASSWORD: "Passw0rd!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_USER: "Developer" 
      MSSQL_PASSWORD: "Devel0per!"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql

# to run the container
# docker-compose up -d
